### ISSUE TITLE
go.work not working

### ISSUE THREAD

**Issue by dncohen** [janpfeifer/gonb#125]
I'm new and experimenting. So far, GoNB looks great!  Thanks so much.

I'm trying to use an unpublished module that I have locally and I've set up `go.work` to use it.

When I put the following in a notebook cell, 

```
!pwd
!go env GOWORK

%goworkfix
```

Then I get `/home/dcohen/work/gonb` from the `!pwd` line (as expected).

And `/home/dcohen/work/gonb/go.work` from the `!go env GOWORK` line (as expected).

But, `executing special commands in cell: there is no go.work file set up, nothing to do` from the `%goworkfix` line.

Any pointers to make GoNB recognize my `go.work`?

**Comment by janpfeifer** [comment]
hi @dncohen , thanks for the encouragement :)

So what I think is wrong in your example is that there are 2 directories to consider:

1. The directory where the notebook is saved, the usual "current" directory.
2. The temporary directory created to hold your cell code -- it's a directory under `tmp` (so if something crashes it gets deleted automatically).

The `!` command executes shell commands in the (1) "current" directory (the one where the notebook is), so there won't be any `go.work` file there.

There is also the `!*` that works the same, but executes the shell command from the (2) "temporary cell code" directory. 

So, [one example](https://github.com/gomlx/gomlx/blob/main/examples/ogbnmag/ogbn-mag.ipynb) of how I use `go.work` follows:

```
!*rm -f go.work && go work init && go work use . "${HOME}/Projects/gomlx" "${HOME}/Projects/gonb"
%goworkfix
```

Notice the `!*` in the shell line. You could achieve the same by doing:

```
!cd ${GONB_TMP_DIR} && rm -f go.work && go work init && go work use . "<my_project_dir>" ...
```

GoNB exposes the temporary cell directory in the `GONB_TMP_DIR` env variable. There are a few other, check `%help` for a list.

I hope this solves your problem -- but let me know if it was something else.

**Comment by dncohen** [comment]
That makes sense and does solve the problem.

Thanks for quick reply.
