### ISSUE TITLE
How to select Go kernel.

### ISSUE THREAD

**Issue by Cactusinhand** [janpfeifer/gonb#127]
I am stuck in the first step of the tutorial.
There is no Go kernel to select, only `ipykernel`, is this the expected?
![image](https://github.com/user-attachments/assets/937b8d5f-3a00-421c-bf78-3c8d32a97173)

Update: I started this by using latest docker image at Windows10

**Comment by janpfeifer** [comment]
hi @Cactusinhand ,

Thanks for the report, this is definitely not expected.

I just quickly freshly downloaded and run [the up-to-date docker ](https://hub.docker.com/r/janpfeifer/gonb_jupyterlab) and things worked as expected, but I'm in a linux box:

![image](https://github.com/user-attachments/assets/db7efca3-9dcc-49e2-9e0d-8f6648f6fa9c)

I wonder if there is something different about how Windows docker runs it !? Unfortunately, I'm travelling right now, and without access to a window machine to try it. But something that looks strange already is that your screenshot has a black background, while the docker jupyter (at least in linux) is configured in white (see my screenshot). Could you be accessing a different port to a different jupyter instance ? What command did you use to run the docker ?

Here (in Linux) I installed and ran the docker with:

```
docker pull janpfeifer/gonb_jupyterlab:latest 
docker run -it --rm -p 8888:8888 -v "${PWD}":/notebooks/host janpfeifer/gonb_jupyterlab:latest
```
