### ISSUE TITLE
Hope to provide gonb Docker images!

### ISSUE THREAD

**Issue by sirliu** [janpfeifer/gonb#13]
As the Title,Hope to provide gonb Docker images!

**Comment by janpfeifer** [comment]
That's a good point @sirliu . I'm working this weekend on a new version (0.5) that will have some improved error reporting/handling. 

Just a heads up that there is going to be a new release soon.

**Comment by sirliu** [comment]
I'm so glad to hear about that~!

> That's a good point @sirliu . I'm working this weekend on a new version (0.5) that will have some improved error reporting/handling.
> 
> Just a heads up that there is going to be a new release soon.

Thank you for your response. I'm so glad to hear this , I hope it will be released soon, and I hope gonb will become more and more popular with richer and richer functions. Thank you again for your hard work.

**Comment by janpfeifer** [comment]
v0.5.0 released. Check it out!

Btw, do you intend to create a `Dockerfile` as well ?

**Comment by janpfeifer** [comment]
With @AnotherCodeArtist help  in #16 , GoNB now has a official docker image -- and a `Dockerfile`.
