### ISSUE TITLE
Some smart GIT integration?

### ISSUE THREAD

**Issue by oderwat** [janpfeifer/gonb#143]
I would like to have gonb to auto-commit (and push) the notebook into a git repository. But only if the code contains changes and it actually was run successfully.

For this I imagine that one adds something like `%git-repo ssh://github.com/oderwat/cool-thing:/notebooks/demo1.ipynb` to the top (or any?) cell. 

This then triggers automatic commits and pushes of the notebook to that git repository.

I think it would need to checkout (and update) the full project for that (`ssh://github.com/oderwat/cool-thing`) and then "ediot" only that filename. GONB could keep that repo somewhere and have different notebooks with the same repo in the same directory.

I also imagine that it only stores the "empty" notebooks (with no results), so that the code is only changed if there really are changes to it.

P.S.: Maybe this could also handle something like updating jupytext from the notebook. I did not think that through though.

P.P.S: If that is to much and specialised functionality. How about adding a hook that can run some code after a sucessful compilation or run of the notebook?

**Comment by janpfeifer** [comment]
Yes, that last `PPS` is what I had in mind. Adding some special magic hook. Maybe something like:

```
%hook <event> <path_to_binary/script>
```

Where `<event>` could include `success` (successful execution), `failure` (failed execution) and `execution` (success or failure), and the given script is run with:

```
<path_to_binary/script> <path_to_notebook.ipynb>
```

Having said that, a couple of things are not explicitly provided by Jupyter to the kernel:

1. Name of the notebook (`.ipynb file`). Gonb is not aware of it, it's all handled within JupyterLab.
2. Functionality to trigger saving the `.ipynb` file is not exposed to the kernel. I suspect one could hack something through Javascript, but that would involve GoNB emitting some javascript as a "pseudo-output" that triggers the save ...

It also feels like this is kernel independent, I wonder if one should write a JupyterLab plugin for that ? That would work in any kernel (including python).

Now, what I would do for a short-term solution is a small program that:

1. Looks for events of a file being saved (the `.ipynb`)
2. Copy/commit `.ipynb` to github whenever it is saved (`control+s` in the jupyter).

And run this in the new `autostart.sh` scheme in the docker (if using the standard docker), or in your own box if running the kernel locally.

p.s.: If you are running notebooks automatically, look at `cmd/nbexec`: it uses a headless chrome to execute the notebook and saves and converts the result for testing. It works pretty nicely.

**Comment by oderwat** [comment]
I personally do not care about **saving** of the NB and do not really care about the name of the notebook. I just want it to run when something was getting **compiled and executed successfully**. Only then I want to create a commit from the actual code and throw away empty commits.

**Comment by janpfeifer** [comment]
Ok, when you say "create a commit from the actual code" you mean the code gonb generates in `${GONB_TMP_DIR}/main.go` right?  

Yes, that should be easy with the `%hook` command. The script will have access to the `$GONB_TMP_DIR` so it can do whatever it wants, sounds pretty trivial.

If that works, let me get to it, after the Docker PR is submitted (maybe before the playing sound PR).

Another use case would be, for instance, to compile the binary and put it, let's say, `~/bin`. So one can code one's scripts using the notebook/gonb. I mean this can already be done (but not automatically after every successful execution), with a cell/line like this:

```
!*go build . -o ~/bin/my_command
```

**Comment by janpfeifer** [comment]
So GoNB doesn't receive the notebook content (or the filename where it is saved), it sees one cell at a time, and it doesn't even know if the cell it is receiving to execute is overwriting a previous one. 

So there isn't a trivial way to get the notebook, or even to tell Jupyter to save it ... since the notebook is not saved after every execution, as far as I know.

Maybe we can inject some javascript to try to instrument JupyterClient, but it's hacky. I already inject a hack like that to work with widgets -- to make them talk directly to the go program -- so i could be appended there somehow. Any thoughts ?

**Comment by janpfeifer** [comment]
Oh, btw, do you want to schedule a quick VC to discuss this ? Maybe it's faster ? Is your email in github working ?

**Comment by oderwat** [comment]
Yes, the email is working.

**Comment by oderwat** [comment]
Given the fact that GoNB is not in a position to do what I imagined I guess such a hook can be useful but not for what I imagined, and I currently do not care to much about it.

I think I need to go another route and found this after some research:

https://gist.github.com/corriebar/cca8a8536bfa04cfa5ea745587b99146

**Comment by janpfeifer** [comment]
Neat. Yes, that makes sense to be in the JupyterServer side.

**Comment by janpfeifer** [comment]
Oh that's is neat! Specially, as they are named after, for collaborative work.

Btw, while the `%hook` is a neat idea, I think until there is a concrete need, I'll close the issue, is that ok ?

**Comment by oderwat** [comment]
> Btw, while the `%hook` is a neat idea, I think until there is a concrete need, I'll close the issue, is that ok ?

Yes
