### ISSUE TITLE
docker pull image source can't not find

### ISSUE THREAD

**Issue by jasonwu513** [janpfeifer/gonb#29]
Is it a spelling error in README.md docker pull ?

What happen :
  Execute docker pull janpfeifer/gonb_jupyter:latest   return error message.

Message:
Error response from daemon: pull access denied for janpfeifer/gonb_jupyter, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

Suggestion:
docker pull janpfeifer/gonb_jupyter:latest => docker pull  janpfeifer/gonb_jupyterlab:latest.

**Comment by janpfeifer** [comment]
Ops, apologies Jason.

The link should be [`janpfeifer/gonb_jupyterlab`](https://hub.docker.com/r/janpfeifer/gonb_jupyterlab).

Does it work for you ?

**Comment by janpfeifer** [comment]
I tested in a couple of other boxes and it seems to work, so closing the issue. But let me know if you find anything else.

Thanks for the report @jasonwu513 !
