### ISSUE TITLE
Better support for error messages in dark mode

### ISSUE THREAD

**Issue by andrewtruong** [janpfeifer/gonb#3]
Hi, thanks for this interesting project!

I'm using this in vscode in dark mode, but the error messages are hard to read.  My hunch is that the background highlighting is a fixed color which works well if the text is dark.
![image](https://user-images.githubusercontent.com/15385696/223608660-0cff3fa2-72c6-4a33-9310-7f33b0c35e92.png)

Here is the same message in light mode:
![image](https://user-images.githubusercontent.com/15385696/223608989-51de75dc-0ad4-45f4-86d0-49e9d6ccf86a.png)

**Comment by janpfeifer** [comment]
hi @andrewtruong , thanks for pointing out!

Took me a bit to figure out the coloring scheme in Jupyter, but it should be fixed. Also VSCode sadly doesn't adhere completely to Jupyter CSS ... fortunately there was an easy fix that worked for both.

It should be there now, in version v0.3.8:

```
$ go install github.com/janpfeifer/gonb@v0.3.8
$ gonb --install
```

And then restart your kernel.

Let me know if you see any issues!

cheers
