### ISSUE TITLE
About integration testing

### ISSUE THREAD

**Issue by oderwat** [janpfeifer/gonb#51]
You write in the README, that you did not find a good way to test with the running notebook. I wrote an (internal) testing package for our PWA using [rod](https://github.com/go-rod/rod). There is some raw example code at [rodgoapp](https://github.com/oderwat/rodgoapp). Maybe this goes into a direction you could use?

**Comment by janpfeifer** [comment]
I didn't know about it, that looks awesome @oderwat , thanks for the pointer. Let me check it out and see if I can make it work and add some tests.

**Comment by janpfeifer** [comment]
Thanks for the pointer! Rod is super cool, I didn't know instrumenting a browser can be made so simple!

By other hand it would still be complex and brittle to instrument Jupyterlab and parse the DOM for the results.

My current plan is, when time allows, to use `nbconvert --execute --to asciidoc ...` for some of the functional tests. But  there are still some things I don't know: how to make it use the gonb kernel being tested (as opposed to the one currently installed in the system).

Any ideas on an easy way to do this (and hopefully have it counted into the coverage) are very welcome :)

**Comment by oderwat** [comment]
Well, for me, this would be more an end to end / integration testing, and we do most of this with [Earthly](https://docs.earthly.dev/docs/guides/integration) which is also how we build packages and deploy stuff. Code coverage is not a measurement we currently really use a lot (sad face).

I guess you know about the integration test coverage that was added with Go 1.20?

https://go.dev/blog/integration-test-coverage

P.S.: I have yet to check out how to use nbconvert myself.

**Comment by janpfeifer** [comment]
Yes, I saw that integration test, actually I spent the morning here trying to use it with `nbconvert`.

The current status is [in the "nbtests" branch](https://github.com/janpfeifer/gonb/tree/nbtests).

And while the integration coverage works ... it doesn't work with the usual unit test coverage 😞, meaning I cannot get an overall coverage number/report (which is useful to drive the writing on tests where needed).

I managed to [hack around](https://github.com/janpfeifer/gonb/blob/nbtests/docs/development.md#generate-coverage). And I also posted [a question in go-nuts@ list](https://groups.google.com/g/golang-nuts/c/tg0ZrfpRMSg), maybe someone will explain how it's done.

I need to write a bit more to finish that change -- it's not actually testing yet, just running `nbconvert` on my test notebooks.

**Comment by janpfeifer** [comment]
Submitted the first few integration tests with `nbconvert` -- covering some past issues. 

Coincidentally in the process of doing that, I caught another subtle bug -- related to `gopls` also receiving and interrupt signal from Jupyter and dying, when a cell was interrupted. Required chaning the process group id when executing `gopls`.

Unfortunately I saw some reports this doesn't work in MacOS, if you notice `gopls` (and auto-complete) stops working after an interrupt (sequence `Esc+I+I` in Jupyterlab), pls let me know.

**Comment by janpfeifer** [comment]
Yes, but the other way around: I use the `-short` for the unit tests, and without the `-short` for the long tests also -- just a matter of convention. In github I configured in actions only the `-short`, so it doesn't take too long (and also so I don't need to configure the complex setup of the needed packages).

Actually, I wish there were more possible levels: tests that run up to 1 sec, up to 10sec, up to 1 minute, up to 10 minutes, etc. This is more critical for me in my other project [GoMLX](https://github.com/gomlx/gomlx), where some of the tests involve training a ML model to a certain quality where (1) it takes time (2) it requires downloading datasets ...

**Comment by oderwat** [comment]
> I use the -short for the unit tests

That is what I mean, if somebody gets the repo and runs `go test ./...` he will start all the integration tests. Using env variables, you can do whatever you want and have as many settings as you want.

**Comment by janpfeifer** [comment]
hey Hans, thanks for creating the issue. I think I'll close it since it seems to be working now. I'll create a new release (v0.7.8) later today.

Having said that, while the framework to do integration tests is there (and coverage went up from 25% to 40%), now I still have lots of testing to write 😄  The report (`docs/coverage.txt`) should help though.
