### ISSUE TITLE
Is the kernel missing in the docker container ?

### ISSUE THREAD

**Issue by martinkunc** [janpfeifer/gonb#59]
Hi Jan, thanks for your work on the kernel in beatiful go :)
I just tried the docker container and it seems the kernel is missing in the environment. Offering just Python 3.
I believe the Dockerfile is missing registering of kerne.json, like over here:
https://github.com/gopherdata/gophernotes/blob/master/Dockerfile#L43

thanks again :)
Martin

**Comment by janpfeifer** [comment]
Thanks for letting me know Martin, I hadn't realized that.

The `gonb --install` does copy itself to Jupyter's directory -- and it seems to be set in the [Dockerfile](https://github.com/janpfeifer/gonb/blob/main/Dockerfile#L49) -- so something else must be wrong. I'll check it first thing tomorrow!

**Comment by janpfeifer** [comment]
hi @martinkunc , I just tried it, and here [the docker](https://hub.docker.com/r/janpfeifer/gonb_jupyterlab) seems to be working fine. I used the standard instructions:

```
docker pull janpfeifer/gonb_jupyterlab:latest
docker run -it --rm -p 8888:8888 -v "${PWD}":/home/jovyan/work janpfeifer/gonb_jupyterlab:latest
```

Did you use the same ? 

cheers

**Comment by martinkunc** [comment]
Hi @janpfeifer , sorry, I forgot to test this yesterday. You are right, it all works as it should. My problem was that I mapped my working folder all over the jovyan's home folder and I haven't realised it uses it to discover local kernel.
What was wrong:
```
docker run -it --rm -p 8888:8888 -v "${pwd}:/home/jovyan" "janpfeifer/gonb_jupyterlab:latest"
```
while the correct way should be as you note:
```
docker run -it --rm -p 8888:8888 -v "${pwd}:/home/jovyan/work" "janpfeifer/gonb_jupyterlab:latest"
```
My sorry and thanks for instant check on your side. Have a good luck with the project!
