### ISSUE TITLE
Just a question about the version differences I get notified about

### ISSUE THREAD

**Issue by oderwat** [janpfeifer/gonb#68]
When I run the latest(?) Jupyter-Lab + gonb I get the line "Adapting from protocol version 5.2 (kernel a8ade612-83a1-4efd-b151-49f5574ae005) to 5.3 (client)". What does this actually mean?

**Comment by janpfeifer** [comment]
I'm not sure. But my guess is that the latest version of JupyterLab (4.0.2 think) may have updated the protocol to 5.3. And GoNB advertises using protocol v5.2 I think.

What is the version of JupyterLab you are using ? And where do you get the message, in the JupyterLab output ?

**Comment by janpfeifer** [comment]
Odd, here I also have:

```
$ jupyter-lab --version
4.0.5
```

But, the included JupyterServer is version 2.7.3:

```
$ jupyter-lab --no-browser
...
[I 2023-09-04 19:36:45.703 ServerApp] Jupyter Server 2.7.3 is running at:
...
```

Now I didn't see in the output you pasted, the line you mentioned about `Adapting from protocol version 5.2 (kernel a8ade612-83a1-4efd-b151-49f5574ae005) to 5.3 (client)`. Does it show it after you start the kernel, in the JupyterLab logs ?

But in anycase, if this is only a warning message in the logs, it should be fine. The protocol from [5.2 to 5.3 changes very little](https://jupyter-client.readthedocs.io/en/latest/messaging.html#id10), in a way that GoNB doesn't use, so it shouldn't matter. But pls let me know if it actually crashes or something.

Btw, GoNB [advertised procotol version number is here](https://github.com/janpfeifer/gonb/blob/main/kernel/kernel.go#L31). But the protocol should be backwards compatible, so all should be fine... (I hope...)

**Comment by oderwat** [comment]
I updated the jupyter-server to 2.7.3 and confirmed that it is being used, but it still reports the same message. But if you are using 5.2 in the kernel, I think it is just saying that the client is newer. I wonder why this is not happening on your machine.

**Comment by janpfeifer** [comment]
Just a quick update that I also see the message now, in the Jupyter logs.

It is innocuous as far as I've seen. And in the upcoming change I'm slowly building, I already updated the advertised protocol version to 5.4 and then it complains in reverse. But also without any functionality issues (the changes are minimal, and don't affect GoNB).

But I'll move the next release to protocol version 5.3 (it's the one I've been using to test the most) so there won't be any warnings.

**Comment by janpfeifer** [comment]
Marking as fixed (I hope) with the new release -- let me know if you see it again.

Btw, check out the new widgets support, it can be handy if experimenting with something interactive.
