### ISSUE TITLE
gonb command is not found following the install commands on the github

### ISSUE THREAD

**Issue by pookiepats** [janpfeifer/gonb#70]
see title, can you please add a little detail around how the final installation should look, where should i see  x, y and z?  it would really help adoption to make the install process as simple as possible without leaning on docker.

reference pocketbase for a simple install process.

❯ go version
go version go1.21.1 linux/amd64
❯ go install github.com/janpfeifer/gonb@latest && \
  go install golang.org/x/tools/cmd/goimports@latest && \
  go install golang.org/x/tools/gopls@latest && \
  gonb --install
go: downloading github.com/janpfeifer/gonb v0.8.0
go: downloading k8s.io/klog/v2 v2.100.1
go: downloading github.com/go-zeromq/zmq4 v0.15.0
go: downloading golang.org/x/exp v0.0.0-20230811145659-89c5cff77bcb
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/gofrs/uuid v4.4.0+incompatible
go: downloading github.com/go-language-server/jsonrpc2 v0.4.2
go: downloading github.com/go-language-server/protocol v0.7.0
go: downloading github.com/go-language-server/uri v0.2.0
go: downloading golang.org/x/mod v0.12.0
go: downloading github.com/fatih/color v1.15.0
go: downloading github.com/mattn/go-isatty v0.0.19
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading golang.org/x/sys v0.11.0
go: downloading github.com/go-logr/logr v1.2.4
go: downloading go.uber.org/zap v1.25.0
go: downloading golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2
go: downloading golang.org/x/text v0.12.0
go: downloading golang.org/x/sync v0.3.0
go: downloading go.uber.org/multierr v1.11.0
go: downloading golang.org/x/tools v0.13.0
go: downloading golang.org/x/sys v0.12.0
go: downloading golang.org/x/tools/gopls v0.13.2
go: downloading honnef.co/go/tools v0.4.2
go: downloading mvdan.cc/gofumpt v0.4.0
go: downloading mvdan.cc/xurls/v2 v2.4.0
go: downloading golang.org/x/tools v0.11.2-0.20230810185051-cc6b5804b8cf
go: downloading golang.org/x/sys v0.10.0
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading golang.org/x/vuln v0.0.0-20230110180137-6ad3e3d07815
go: downloading golang.org/x/text v0.11.0
go: downloading github.com/google/go-cmp v0.5.9
go: downloading golang.org/x/exp/typeparams v0.0.0-20221212164502-fae10dda9338
go: downloading github.com/BurntSushi/toml v1.2.1
go: downloading golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e
# zsh: command not found: gonb
❯ gonb
zsh: command not found: gonb
❯ go

**Comment by pookiepats** [comment]
> gonb --install
zsh: command not found: gonb

**Comment by pookiepats** [comment]
figured it out, please be aware installing GO using the standard docs instructions on go.dev DOES NOT SET YOUR  GOPATH let alone the compiled commands in GOPATH/bin - sweet library but this took 30 minutes of research.

If you want noobs and others to adopt this I would assume this is NOT common knowledge or at least not entirely obvious.

Neither too is installing Docker these days because of 9000 different Docker methods on their own docs - so please if you're going to tout something as trivial - just make sure it actually is.

**Comment by janpfeifer** [comment]
Thanks for pointing it out @pookiepats . Since I use Go often my GOPATH/bin is already in my PATH variable, and things just work, and I incorrectly assumed the same.

You are right, I'll update the documentation for newcomers to Go.

**Comment by janpfeifer** [comment]
Updated the **GoNB** installation documentation using the standard Go tools (not yet the Docker), it's in a branch for now, but will be merged soon on a new release of GoNB.

[Here the new version](https://github.com/janpfeifer/gonb/tree/wasm2) -- it also includes some other upcoming new features.
