### ISSUE TITLE
Notebook 7.0.5 cell log output in a red background

### ISSUE THREAD

**Issue by olablt** [janpfeifer/gonb#77]
The log output always appears with a red background. How can I fix this?

![image](https://github.com/janpfeifer/gonb/assets/674574/e3843ce4-6e83-48ae-a06d-a9be62e5f61b)

**Comment by oderwat** [comment]
I made it in one of our loggers so that logging to stderr is "red" and stdio is "white" always. You can easily make log.* go to stderr or stdout and as such could distinguish between error states and normal output.

**Comment by janpfeifer** [comment]
Oh, cool, so it's all good, right ?

cheers!

**Comment by olablt** [comment]
![image](https://github.com/janpfeifer/gonb/assets/674574/c21bdc32-3351-4203-b08f-e9d7f52f4063)
