### ISSUE TITLE
Doesn't work in Google Colab

### ISSUE THREAD

**Issue by keys4words** [janpfeifer/gonb#80]
![colab](https://github.com/janpfeifer/gonb/assets/25738245/99c1d1b8-0710-43fe-b8c3-ea589d6d381f)

**Comment by janpfeifer** [comment]
Btw, I think it was a very minimal thing (I managed to fix over coffee). When you can, pls check it out if it works for you!

**Comment by keys4words** [comment]
Thank you, Jan!
