### ISSUE TITLE
Mac Installation

### ISSUE THREAD

**Issue by akhenakh** [janpfeifer/gonb#9]
The README is not obvious, I've first tried it on Linux, then realized it's not working by itself on Mac.

The proper path on Mac to install the kernel is: /Users/${USER}/Library/Jupyter/kernels/

For the folks on Mac after gonb --install,  just move the kernel definition to:

```
 mv /Users/${USER}/.local/share/jupyter/kernels/gonb  /Users/${USER}/Library/Jupyter/kernels/
```

Great work thanks for gonb!

**Comment by janpfeifer** [comment]
hi @akhenakh , thanks for the feedback. Indeed I point out in the *TODO* section that I never tested it in Mac and likely it won't work -- but in retrospect I should have mentioned it in the INSTALL section, my bad.

Question: if I do a change that tries to install correctly in Mac (by creating the Jupyter configuration file in `/Users/${USER}/Library/Jupyter/kernels/`), would you be willing to test it ?

**Comment by janpfeifer** [comment]
I hope that PR should do the installation to the right location in Macs. Would you be able to test with something like:

```
$ go install github.com/janpfeifer/gonb@4c25cbb99dd509a194e71f67d16acb5369503628
$ gonb --install --logtostderr
```

And check that it updated the  `/Users/${USER}/Library/Jupyter/kernels/` file ? 

thanks!

**Comment by akhenakh** [comment]
Cleaned up before installing:
```
rm -r /Users/${USER}/.local/share/jupyter
rm -r /Users/${USER}/Library/Jupyter/kernels/gonb
```
Confirmed it's disabled in Jupyter
```
go install github.com/janpfeifer/gonb@4c25cbb99dd509a194e71f67d16acb5369503628 
go: downloading github.com/janpfeifer/gonb v0.4.1-0.20230324081946-4c25cbb99dd5

gonb --install --logtostderr
[50d4168f] 2023/03/24 07:21:27 Go (gonb) kernel configuration installed in "/Users/xxx/Library/Jupyter/kernels/kernel.json".
```

It does not show up in jupyter, I think it's missing one more directory it should be `/Users/xxx/Library/Jupyter/kernels/gonb/kernel.json"`

**Comment by janpfeifer** [comment]
Ugh, my bad. Thanks for checking!

 I'll send a new version later tonight.

**Comment by janpfeifer** [comment]
Again apologies. The new attempt is:

```
$ go install github.com/janpfeifer/gonb@bb9ef92ca3cb186ff747e194ad1a13f52b229a85
```

Would you mind trying again ?

**Comment by akhenakh** [comment]
```
[6ce2567e] 2023/03/24 17:32:51 Go (gonb) kernel configuration installed in "/Users/xxx/Library/Jupyter/kernels/gonb/kernel.json".
```

And it's working !

Thanks
