### ISSUE TITLE
Is there plan to implement some hack print like gruns/icecream

### ISSUE THREAD

**Issue by potoo0** [janpfeifer/gonb#98]
[icecream#inspect-variables](https://github.com/gruns/icecream#inspect-variables)

expected:
```go
func genInt() int {
  return 1
}
s := "hello"

dev.Print(s, genInt()) // s: hello, genInt(): 1
```

**Comment by janpfeifer** [comment]
hi @potoo0 ,

I didn't know about `icecream`, thanks for bringing it up -- it seems a very useful tool.

 But it seems to work well (mostly) in `gonb`, check out:

![image](https://github.com/janpfeifer/gonb/assets/7460115/c6785005-d45b-4466-a959-5874c9ec74e2)

(Notice the bug with `Ic()` with no parameters, but I suspect that doesn't matter much ?)

Were you looking for something else ?

cheers

**Comment by potoo0** [comment]
Sorry, I didn't do enough digging.
My first idea was to use ast to rewrite `dev.Print(...)` as `fmt.Printf(<pattern>, ...)`, after the cell code is written to the file.

I also implemented a simple version, but it seems unnecessary after this.

```go
selX.Name = "fmt"
sel.Sel.Name = "Printf"
label := identLabel(fset, expr)
expr.Args = append([]ast.Expr{&ast.BasicLit{Kind: token.STRING, Value: label}}, expr.Args...)
// ...
// format.Node overwrite main.go


// identLabel ...
for idx, arg := range expr.Args {
  builder.WriteString(AnsiCyan)
  err := printer.Fprint(&builder, fset, arg)
  if err != nil {
    builder.WriteString("-")
  }
  builder.WriteString(AnsiReset)
  builder.WriteString(": %+v")
  if idx+1 != argLen {
    builder.WriteString(", ")
  }
}
```
